version: "3"
services:
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        hostname: zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        hostname: kafka
        ports:
            - "9092:9092"
        expose:
            - "9093"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "topic_hello:1:1"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    
    producer:
        build: ./producer
        container_name: producer
        depends_on: 
            - zookeeper
            - kafka

    consumer:
        build: ./consumer
        container_name: consumer
        depends_on: 
            - zookeeper
            - kafka
            - producer
