version: "3"
services:    
    zookeeper:
        image: wurstmeister/zookeeper
        container_name: zookeeper
        hostname: zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        hostname: kafka
        ports:
            - "9092:9092"
        expose:
            - "9093"
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "topic_detector:1:1"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

    mqtt:
        image: toke/mosquitto
        hostname: mosquitto
        container_name: mqtt
        expose:
            - 1883
        ports:
            - 1883:1883
        restart: always
        privileged: true

    mqtt-subscriber:
        build: ./mqtt-subscriber
        container_name: mqtt-subscriber
        privileged: true
        depends_on:
            - zookeeper
            - kafka
            - mqtt

    kafka-consumer:
        build: ./kafka-consumer
        container_name: kafka-consumer
        depends_on: 
            - mqtt-subscriber

    detector:
        build: ./detector
        container_name: detector
        environment:
            - DISPLAY=$DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
        privileged: true
        depends_on: 
            - kafka-consumer
